<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>KarTime</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KarTime.Domain\KarTime.Domain.csproj" />
    <ProjectReference Include="..\KarTime.Application.Contracts\KarTime.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.0.2" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.0.2" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.0.2" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.0.2" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.0.2" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="10.0.2" />
  </ItemGroup>

</Project>
